name: CI/CD for C++ to itch.io

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Set up MinGW
        run: |
          choco install mingw --version=13.2.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
  
      - name: Verify MinGW installation
        run: g++ --version
  
      - name: Clean previous build
        run: if (Test-Path -Path "cmake-build-debug") { Remove-Item -Recurse -Force "cmake-build-debug" }
  
      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Release
  
      - name: Build
        run: cmake --build cmake-build-debug --config Release

      - name: Download certificate
        run: echo "${{ secrets.CERT }}" > code_signing_cert.pfx

      - name: Install Windows SDK
        run: choco install windows-sdk-10-version-1903-all

      - name: Sign the executable
        run: |
          signtool sign /f code_signing_cert.pfx /p ${{ secrets.CERT_PASSWORD }} /t http://timestamp.digicert.com cmake-build-debug/ASCII_Game.exe
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ascii-game
          path: cmake-build-debug/ASCII_Game.exe
  
  upload:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ascii-game
          path: .
  
      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/latest/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin
  
      - name: Upload to Itch.io
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          butler push ASCII_Game.exe your-itch-username/your-game-name:windows
