name: CI/CD for C++ to itch.io

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Set up MinGW
        run: |
          choco install mingw
          refreshenv
  
      - name: Add MinGW to PATH
        run: echo "::add-path::C:\tools\mingw64\bin"
  
      - name: Verify MinGW installation
        run: g++ --version
  
      - name: Clean previous build
        run: if (Test-Path -Path "cmake-build-debug") { Remove-Item -Recurse -Force "cmake-build-debug" }
  
      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug
  
      - name: Build
        run: cmake --build cmake-build-debug --config Debug

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ascii-game
          path: '**/ASCII_Game.exe'
  
  upload:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ascii-game
          path: .
  
      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/latest/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin
  
      - name: Upload to Itch.io
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          butler push ASCII_Game.exe your-itch-username/your-game-name:windows
