name: CI/CD for C++ to itch.io

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Set up MinGW
        run: |
          choco install mingw --version=13.2.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
  
      - name: Verify MinGW installation
        run: g++ --version
  
      - name: Clean previous build
        run: if (Test-Path -Path "cmake-build-debug") { Remove-Item -Recurse -Force "cmake-build-debug" }
  
      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Release
  
      - name: Build
        run: cmake --build cmake-build-debug --config Release
  
      - name: Package executable and dependencies
        run: |
          cd cmake-build-debug
          # Copy any necessary DLLs here (e.g., libstdc++-6.dll, libgcc_s_seh-1.dll)
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ascii-game
          path: cmake-build-debug/ASCII_Game.exe
  
  upload:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ascii-game
          path: .

      - name: Install Butler
        run: |
          BUTLER_VERSION=$(curl -s https://broth.itch.ovh/butler/latest-metadata.json | jq -r .version)
          BUTLER_URL="https://broth.itch.ovh/butler/${BUTLER_VERSION}/archive/default/butler-linux-amd64.tar.gz"
          curl -L -o butler.tar.gz $BUTLER_URL
          tar -xzf butler.tar.gz -C /usr/local/bin
          butler --version
  
      - name: Upload to Itch.io
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          butler push ASCII_Game.exe szotkowski/ascii-game:windows
